def generate_readme(report_data, output_path="README.md"):
    """
    Auto-generates a README.md summarizing the code analysis results.
    Pulls everything from the same report_data dict used by the
    JSON and HTML reports.
    """

    health = report_data["health_report"]
    security = report_data["security_report"]

    content = f"""# Code Analysis Report

This README was auto-generated by the Code Intelligence Tool.

## Overall Code Health

- **Overall Score:** {health['overall_score']}%
- **Grade:** {health['grade']}
- **Complexity Rating:** {report_data['rating']}
- **Maintainability Score:** {report_data['maintainability_score']}%
- **Security Score:** {security['score']}% ({security['rating']})

## Project Summary

| Metric | Value |
|---|---|
| Functions | {report_data['functions']} |
| Classes | {report_data['classes']} |
| Imports | {report_data['imports']} |
| Total Lines | {report_data['total_lines']} |
| Code Lines | {report_data['code_lines']} |
| Blank Lines | {report_data['blank_lines']} |
| Comment Lines | {report_data['comment_lines']} |
| Complexity Score | {report_data['complexity']} |

## Function Metrics

- **Largest Function:** {report_data['largest_function']}
- **Smallest Function:** {report_data['smallest_function']}
- **Average Function Size:** {report_data['average_function_size']:.2f} lines

## Issues Found

| Category | Count |
|---|---|
| Duplicate Functions | {len(report_data['duplicate_functions'])} |
| Unused Imports | {len(report_data['unused_imports'])} |
| Unused Variables | {len(report_data['unused_variables'])} |
| Missing Docstrings | {len(report_data['missing_docstrings'])} |
| Long Functions | {len(report_data['long_functions_detected'])} |
| Empty Exception Handlers | {len(report_data['empty_exception_handlers'])} |
| Global Variables | {len(report_data['global_variables'])} |
| Dead Code | {len(report_data['dead_code'])} |
| Hardcoded Passwords | {len(report_data['hardcoded_passwords'])} |
| Large Classes | {len(report_data['large_classes'])} |

## Task Comments

- TODO: {report_data['todo_comments']}
- FIXME: {report_data['fixme_comments']}
- BUG: {report_data['bug_comments']}

## Detected Requirements

{chr(10).join(f"- {pkg}" for pkg in report_data['requirements']) if report_data['requirements'] else "- No third-party packages detected."}

## How to Run

```bash
python main.py
```

Reports generated:
- `report.json` — full machine-readable report
- `report.html` — visual dashboard
- `summary_chart.png` — summary chart image

## Known Limitations

- Dead code detection may report false positives for dynamically used code (e.g. `getattr`, decorators, re-exports).
- Duplicate detection only catches exact matches, not renamed-variable near-duplicates.
- Complex module-level logic outside functions/classes is not deeply analyzed.
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print("README.md generated successfully.")

    return content


if __name__ == "__main__":
    sample_report_data = {
        "health_report": {"overall_score": 83.5, "grade": "B"},
        "security_report": {"score": 90, "rating": "Good"},
        "rating": "Good",
        "maintainability_score": 78,
        "functions": 20,
        "classes": 4,
        "imports": 15,
        "total_lines": 500,
        "code_lines": 400,
        "blank_lines": 60,
        "comment_lines": 40,
        "complexity": 18,
        "largest_function": "process_data (40 lines)",
        "smallest_function": "get_id (1 line)",
        "average_function_size": 12.5,
        "duplicate_functions": [],
        "unused_imports": ["os"],
        "unused_variables": [],
        "missing_docstrings": ["helper"],
        "long_functions_detected": [],
        "empty_exception_handlers": [],
        "global_variables": [],
        "dead_code": [],
        "hardcoded_passwords": [],
        "large_classes": [],
        "todo_comments": 2,
        "fixme_comments": 1,
        "bug_comments": 0,
        "requirements": ["flask", "requests"]
    }
    generate_readme(sample_report_data, "test_README.md")
