import ast
import sys

try:
    STDLIB_MODULES = set(sys.stdlib_module_names)
except AttributeError:
    # Fallback for Python < 3.10
    STDLIB_MODULES = {
        "os", "sys", "re", "math", "json", "ast", "time", "datetime",
        "collections", "itertools", "functools", "typing", "pathlib",
        "hashlib", "random", "string", "subprocess", "logging", "argparse",
        "unittest", "io", "shutil", "copy", "csv", "sqlite3", "threading",
        "multiprocessing", "socket", "http", "urllib", "email", "xml",
        "html", "abc", "enum", "dataclasses", "traceback", "warnings",
        "inspect", "importlib", "pickle", "base64", "struct", "queue"
    }


def extract_imports(code):
    """
    Extracts top-level imported module names from source code.
    """
    tree = ast.parse(code)
    modules = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                modules.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.level == 0:
                modules.add(node.module.split(".")[0])

    return modules


def generate_requirements(python_files, read_file_func, output_path="requirements.txt"):
    """
    Scans all project files and writes a requirements.txt containing
    only third-party (non standard-library) packages.

    python_files: list of file paths (e.g. from your file_reader.get_python_files)
    read_file_func: a function that takes a path and returns source code
                     (pass your existing reader.read_file)
    """
    all_modules = set()

    for file_path in python_files:
        code = read_file_func(file_path)
        try:
            all_modules.update(extract_imports(code))
        except SyntaxError:
            continue

    third_party = sorted(
        m for m in all_modules
        if m not in STDLIB_MODULES and not m.startswith("_")
    )

    with open(output_path, "w") as f:
        f.write("# Auto-generated by requirements_generator.py\n")
        f.write("# Review and pin exact versions with 'pip freeze' if needed\n\n")
        for module in third_party:
            f.write(module + "\n")

    return third_party


if __name__ == "__main__":
    sample_files = {
        "a.py": "import os\nimport requests\nfrom flask import Flask\n",
        "b.py": "import json\nimport numpy as np\n"
    }

    def fake_reader(path):
        return sample_files[path]

    result = generate_requirements(list(sample_files.keys()), fake_reader, "test_requirements.txt")
    print(result)
